version: "3.6"
services:
  django:
    image: cyface/docker-demo:latest
    environment:
      MAGIC_MESSAGE: Docker Compose Image Pull
    ports:
      - "8000:8000"
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - django
