version: "3.6"
services:
  django:
    image: cyface/docker-demo:latest
    environment:
      MAGIC_MESSAGE: Docker Compose Image Pull
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./statics:/web/statics:ro
    depends_on:
      - django
